### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by umbrellacorp03** [PoC-Consortium/Qbundle#34]
Hello,

I'm testing the new Qbundle 2.0.0 wallet on Windows 10 Pro 64 bits.

I don't know if this "issue" was already reported but :
The problem is that I clicked on "Check for updates" and everything was up to date, then the following message apears on a new window when trying to close the "check for update" window : 

"Do you want to stop the wallet?
It must be stopped before updating the components."

Why this message when everything is already up to date ?

![check for updates](https://user-images.githubusercontent.com/35744417/37971252-c64d4d94-31d5-11e8-8394-fe0715142a09.png)

**Comment by Quibus-burst** [comment]
This should be fixed in 2.0.1

**Comment by umbrellacorp03** [comment]
Hi, it's me again !

This issue is still present on 2.0.1...

**Comment by Quibus-burst** [comment]
Alright. when wallet is running the question is asked. It is not supposed to be like that no. In 2.0.0 it was asked even if wallet was stoped thats why I did not get it. I will keep issue open untill i commit a fix.

For now you can hit the X in the top right corner to close or say no to the question to continue normal operation.
